## Decision Function

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=42)

gbrt = GradientBoostingClassifier(learning_rate=0.01, random_state=0)
gbrt.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.01, random_state=0)

In [4]:
print("Decision function shape: {}".format(gbrt.decision_function(X_test).shape))

# plotting first few entries of the the decision function
print("Decision Function:\n{}".format(gbrt.decision_function(X_test)[:6, :]))

Decision function shape: (38, 3)
Decision Function:
[[-1.995715    0.04758267 -1.92720695]
 [ 0.06146394 -1.90755736 -1.92793758]
 [-1.99058203 -1.87637861  0.09686725]
 [-1.995715    0.04758267 -1.92720695]
 [-1.99730159 -0.13469108 -1.20341483]
 [ 0.06146394 -1.90755736 -1.92793758]]


In [6]:
import numpy as np

print("ArgMax of decision function:\n{}".format(
    np.argmax(gbrt.decision_function(X_test), axis =1)))

print("Predictions: \n{}".format(gbrt.predict(X_test)))

ArgMax of decision function:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]
Predictions: 
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]


## Predicted Probabilities

In [7]:
# showing the few entries of the predict_proba
print("Predicted probabilites:\n{}".format(gbrt.predict_proba(X_test)[:6]))

# Showing the sums across rows are one
print("Sums: {}".format(gbrt.predict_proba(X_test)[:6].sum(axis=1)))

Predicted probabilites:
[[0.10217718 0.78840034 0.10942248]
 [0.78347147 0.10936745 0.10716108]
 [0.09818072 0.11005864 0.79176065]
 [0.10217718 0.78840034 0.10942248]
 [0.10360005 0.66723901 0.22916094]
 [0.78347147 0.10936745 0.10716108]]
Sums: [1. 1. 1. 1. 1. 1.]


In [8]:
print("ArgMax of predicted probabilities:\n{}".format(
    np.argmax(gbrt.predict_proba(X_test), axis =1)))

print("Predictions: \n{}".format(gbrt.predict(X_test)))

ArgMax of predicted probabilities:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]
Predictions: 
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]


### Logistic Regression

In [9]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

# Representing each target by it's class names in the iris dataset
named_target = iris.target_names[y_train]
logreg.fit(X_train, named_target)

print("Unique Classes in training data: {}".format(logreg.classes_))
print("Predicitions: {}".format(logreg.predict(X_test)[:10]))

argmax_dec_func = np.argmax(logreg.decision_function(X_test), axis=1)

print("ArgMax of decision function: {}".format(argmax_dec_func[:10]))
print("ArgMax combined with the classes: {}".format(logreg.classes_[argmax_dec_func][:10]))

Unique Classes in training data: ['setosa' 'versicolor' 'virginica']
Predicitions: ['versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor']
ArgMax of decision function: [1 0 2 1 1 0 1 2 1 1]
ArgMax combined with the classes: ['versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor']
